// Autogenerated from Pigeon (v9.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif



private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TactileFeedbackApi {
  func impact() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TactileFeedbackApiSetup {
  /// The codec used by TactileFeedbackApi.
  /// Sets up an instance of `TactileFeedbackApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TactileFeedbackApi?) {
    let impactChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.TactileFeedbackApi.impact", binaryMessenger: binaryMessenger)
    if let api = api {
      impactChannel.setMessageHandler { _, reply in
        do {
          try api.impact()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      impactChannel.setMessageHandler(nil)
    }
  }
}
